global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.3:8085']
        labels:
          application: 'Producto Service Application'
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.3:8084']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventario-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.3:8082']
        labels:
          application: 'Inventario Service Application'
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.3:8086']
        labels:
          application: 'Notification Service Application'
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.3:8087']
        labels:
          application: 'Message Service Application'
